const ISSUES = {
    CREATE_ISSUES: 'CREATE_ISSUES',
    EDIT_ISSUES: 'EDIT_ISSUES',
    DELETE_ISSUES: 'DELETE_ISSUES',
    GET_ISSUES: 'GET_ISSUES'
}

const USERS_PROFILE = {
    GET_USERS_PROFILES: 'GET_USERS_PROFILES'
}

export {
    ISSUES, USERS_PROFILE
}